#!/usr/bin/env bash
#
# Generate THIRD_PARTY_NOTICES.md — license attribution for the third-party
# open-source components bundled in the SHIPPED artifacts:
#   * backend  → Python production dependencies (uv, --no-dev)
#   * frontend → npm production dependencies     (license-checker, --production)
#
# Dev/build-only dependencies (pytest, ruff, vite, eslint, playwright, …) are
# intentionally excluded — they are not distributed in the production images.
#
# Requirements: uv, node/npx. Everything runs in throwaway environments, so
# your local .venv / node_modules are not modified.
#
# Usage: ./scripts/generate-third-party-notices.sh
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="THIRD_PARTY_NOTICES.md"
TMP_REQS="$(mktemp)"
trap 'rm -f "$TMP_REQS"' EXIT

VERSION="$(grep -m1 '^version = ' pyproject.toml | cut -d'"' -f2)"

echo "Exporting backend production dependencies…"
uv export --no-dev --no-emit-project --format requirements-txt > "$TMP_REQS"

echo "Collecting backend licenses…"
BACKEND_TABLE="$(uvx --with-requirements "$TMP_REQS" --with pip-licenses \
  pip-licenses --format=markdown --with-urls --order=license)"

echo "Collecting frontend licenses…"
# --excludePrivatePackages drops the project's own package (marked
# "private": true) — it is the project, not a bundled dependency.
FRONTEND_LIST="$(npx --yes license-checker-rseidelsohn \
  --production --start . --markdown --excludePrivatePackages)"

# license-checker walks the installed tree: without node_modules it reports an
# empty list instead of failing, which would silently drop the whole frontend
# section from the notices.
if [ -z "$FRONTEND_LIST" ]; then
  echo "No frontend licenses found — run 'npm ci' first." >&2
  exit 1
fi

# Per-platform native binary variants (…-darwin-arm64, …-linux-x64-gnu,
# fsevents) depend on the machine the script runs on, so keeping them would
# make the output differ between a developer laptop and CI. Their parent
# packages (lightningcss, @tailwindcss/oxide, rolldown, …) stay listed and
# carry the same license.
FRONTEND_LIST="$(printf '%s\n' "$FRONTEND_LIST" | grep -Ev -- \
  '-(darwin|linux|win32|freebsd|openbsd|netbsd|android|sunos|aix)-(arm64|arm|x64|ia32|ppc64|riscv64|s390x|loong64|mips64el|wasm32)|\[fsevents@')"

{
  echo "# Third-Party Notices"
  echo
  echo "The Medical Document Anonymizer (version \`${VERSION}\`) is distributed"
  echo "under the \`AGPL-3.0-or-later\` license. It bundles the third-party"
  echo "open-source components listed below, each governed by its own license."
  echo "Full license texts are available in each project's repository (linked"
  echo "below) and in the installed package metadata."
  echo
  echo "> This file is generated by \`scripts/generate-third-party-notices.sh\`."
  echo "> Do not edit it by hand — re-run the script to refresh it."
  echo
  echo "Only dependencies shipped in the production build are listed."
  echo "Development and build-time tooling (test frameworks, bundlers, linters)"
  echo "is excluded because it is not distributed."
  echo
  echo "## Backend (Python — production dependencies)"
  echo
  echo "$BACKEND_TABLE"
  echo
  echo "## Frontend (npm — production dependencies)"
  echo
  echo "$FRONTEND_LIST"
} > "$OUT"

echo "Wrote $OUT"
